#!/usr/bin/env python3
"""
Mythos Skill Forge — scaffold production-ready Claude Code skills.

Generates a complete skill directory with SKILL.md, CLAUDE.md, hooks,
and templates following Anthropic's skill conventions.
"""

import argparse
import os
import re
import sys
import textwrap
from dataclasses import dataclass
from pathlib import Path


@dataclass
class SkillSpec:
    """Specification for a Claude Code skill."""
    name: str
    title: str
    description: str
    triggers: list[str]
    steps: list[str]
    category: str = "general"
    hooks: bool = False
    templates: bool = False

    def validate(self) -> list[str]:
        """Validate the skill spec against Anthropic conventions."""
        errors = []
        if not re.match(r"^[a-z][a-z0-9_]{0,58}$", self.name):
            errors.append(f"Name '{self.name}' must be snake_case, start with a letter, max 60 chars")
        if len(self.triggers) < 3:
            errors.append(f"Need at least 3 trigger phrases, got {len(self.triggers)}")
        if len(self.triggers) > 5:
            errors.append(f"Recommend at most 5 trigger phrases, got {len(self.triggers)}")
        if len(self.steps) < 2:
            errors.append(f"Need at least 2 workflow steps, got {len(self.steps)}")
        if not self.description.strip():
            errors.append("Description cannot be empty")
        if len(self.description) > 500:
            errors.append(f"Description too long ({len(self.description)} chars), max 500")
        return errors


def generate_skill_md(spec: SkillSpec) -> str:
    """Generate the SKILL.md content."""
    trigger_list = ", ".join(f'"{t}"' for t in spec.triggers)
    when_to_use = "\n".join(f'- "{t}"' for t in spec.triggers)
    steps_md = "\n".join(f"### Step {i+1}: {s}" for i, s in enumerate(spec.steps))

    return textwrap.dedent(f"""\
    ---
    name: {spec.name}
    description: |
      {spec.description}
      Triggers: {trigger_list}
    ---

    # {spec.title}

    {spec.description}

    ## When to use

    {when_to_use}

    ## How to use

    {steps_md}

    ## References

    - Generated by Mythos Skill Forge
    - Anthropic skill conventions: https://github.com/anthropics/skills
    """)


def generate_claude_md(spec: SkillSpec) -> str:
    """Generate a CLAUDE.md for the skill directory."""
    return textwrap.dedent(f"""\
    # {spec.title} — Agent Instructions

    This skill was generated by Mythos Skill Forge.

    ## Context

    - **Category**: {spec.category}
    - **Triggers**: {', '.join(spec.triggers)}

    ## Behavior

    When triggered, follow the steps in SKILL.md exactly.
    Do not skip validation or output steps.

    ## Constraints

    - Stay within the skill's scope — do not perform unrelated actions.
    - If a step fails, report the failure clearly before continuing.
    - Prefer generating files over printing to stdout for large outputs.
    """)


def generate_hook(hook_type: str, spec: SkillSpec) -> str:
    """Generate a pre or post hook script."""
    if hook_type == "pre":
        return textwrap.dedent(f"""\
        #!/bin/sh
        # Pre-execution hook for {spec.name}
        # Runs before the skill executes.
        echo "[{spec.name}] Pre-hook: validating environment..."
        # Add pre-checks here (e.g., required tools, files, permissions)
        exit 0
        """)
    else:
        return textwrap.dedent(f"""\
        #!/bin/sh
        # Post-execution hook for {spec.name}
        # Runs after the skill completes.
        echo "[{spec.name}] Post-hook: cleaning up..."
        # Add post-processing here (e.g., formatting, notifications)
        exit 0
        """)


def generate_template(spec: SkillSpec) -> str:
    """Generate a default output template."""
    return textwrap.dedent(f"""\
    # {{{{ title }}}}

    > Generated by **{spec.title}**

    ## Summary

    {{{{ summary }}}}

    ## Details

    {{{{ details }}}}

    ---
    _Produced by {spec.name} skill_
    """)


def forge_skill(spec: SkillSpec, output_dir: Path, dry_run: bool = False) -> dict:
    """
    Forge a complete skill directory structure.

    Returns a dict of {relative_path: content} for all generated files.
    """
    errors = spec.validate()
    if errors:
        return {"_errors": errors}

    skill_dir = output_dir / spec.name
    files = {}

    # Core files
    files[f"{spec.name}/SKILL.md"] = generate_skill_md(spec)
    files[f"{spec.name}/CLAUDE.md"] = generate_claude_md(spec)

    # Optional hooks
    if spec.hooks:
        files[f"{spec.name}/hooks/pre_run.sh"] = generate_hook("pre", spec)
        files[f"{spec.name}/hooks/post_run.sh"] = generate_hook("post", spec)

    # Optional templates
    if spec.templates:
        files[f"{spec.name}/templates/default.md"] = generate_template(spec)

    if dry_run:
        return files

    # Write files to disk
    for rel_path, content in files.items():
        full_path = output_dir / rel_path
        full_path.parent.mkdir(parents=True, exist_ok=True)
        full_path.write_text(content)
        if rel_path.endswith(".sh"):
            full_path.chmod(0o755)

    return files


def audit_skill(skill_dir: Path) -> dict:
    """
    Audit an existing skill directory for convention compliance.

    Returns a report dict with score and issues.
    """
    report = {"path": str(skill_dir), "score": 0, "max_score": 5, "issues": [], "passes": []}

    skill_md = skill_dir / "SKILL.md"
    if not skill_md.exists():
        report["issues"].append("Missing SKILL.md")
        return report

    content = skill_md.read_text()

    # Check 1: YAML frontmatter with name and description
    if content.startswith("---"):
        fm_end = content.find("---", 3)
        if fm_end > 0:
            frontmatter = content[3:fm_end]
            if "name:" in frontmatter and "description:" in frontmatter:
                report["passes"].append("YAML frontmatter has name and description")
                report["score"] += 1
            else:
                report["issues"].append("Frontmatter missing 'name' or 'description'")
            if "Triggers:" in frontmatter or "triggers:" in frontmatter.lower():
                report["passes"].append("Triggers defined in frontmatter")
                report["score"] += 1
            else:
                report["issues"].append("No trigger phrases in frontmatter description")
        else:
            report["issues"].append("Malformed YAML frontmatter (no closing ---)")
    else:
        report["issues"].append("Missing YAML frontmatter")

    # Check 2: When to use section
    if "## When to use" in content:
        when_section = content.split("## When to use")[1].split("##")[0]
        bullet_count = when_section.count("\n-")
        if bullet_count >= 3:
            report["passes"].append(f"'When to use' has {bullet_count} trigger phrases")
            report["score"] += 1
        else:
            report["issues"].append(f"'When to use' has only {bullet_count} triggers (need 3+)")
    else:
        report["issues"].append("Missing '## When to use' section")

    # Check 3: How to use section
    if "## How to use" in content:
        report["passes"].append("'How to use' section present")
        report["score"] += 1
    else:
        report["issues"].append("Missing '## How to use' section")

    # Check 4: No placeholder text
    placeholders = ["TODO", "FIXME", "placeholder", "<your", "lorem ipsum"]
    found = [p for p in placeholders if p.lower() in content.lower()]
    if not found:
        report["passes"].append("No placeholder text detected")
        report["score"] += 1
    else:
        report["issues"].append(f"Placeholder text found: {', '.join(found)}")

    return report


def print_report(report: dict):
    """Pretty-print an audit report."""
    print(f"\n{'='*60}")
    print(f"  Skill Audit: {report['path']}")
    print(f"  Score: {report['score']}/{report['max_score']}")
    print(f"{'='*60}")
    if report["passes"]:
        print("\n  PASS:")
        for p in report["passes"]:
            print(f"    [+] {p}")
    if report["issues"]:
        print("\n  ISSUES:")
        for i in report["issues"]:
            print(f"    [-] {i}")
    print()


def print_tree(files: dict, base: str = ""):
    """Print a directory tree of generated files."""
    print(f"\n  Generated skill structure:")
    print(f"  {'='*40}")
    for path in sorted(files.keys()):
        if path.startswith("_"):
            continue
        depth = path.count("/")
        indent = "  " * depth
        name = path.split("/")[-1]
        print(f"    {indent}{name}")
    print()


# --- Preset skill templates for demo ---

PRESETS = {
    "code_review": SkillSpec(
        name="code_review_agent",
        title="Code Review Agent",
        description="Performs automated code review with security, style, and correctness checks.",
        triggers=[
            "review this code",
            "do a code review",
            "check this PR for issues",
            "audit this file for bugs",
        ],
        steps=[
            "Identify the files to review (staged changes or specified paths)",
            "Analyze for security vulnerabilities (injection, auth, secrets)",
            "Check code style and consistency against project conventions",
            "Evaluate correctness and edge case handling",
            "Generate a structured review report with severity levels",
        ],
        category="development",
        hooks=True,
        templates=True,
    ),
    "deploy_checklist": SkillSpec(
        name="deploy_checklist",
        title="Deploy Checklist",
        description="Generates and validates a pre-deployment checklist for production releases.",
        triggers=[
            "run deploy checklist",
            "pre-deploy check",
            "validate deployment readiness",
        ],
        steps=[
            "Scan for uncommitted changes and unpushed branches",
            "Verify tests pass and coverage meets thresholds",
            "Check environment variables and secrets configuration",
            "Validate database migrations are up to date",
            "Generate go/no-go deployment report",
        ],
        category="devops",
        hooks=True,
    ),
    "api_doc_gen": SkillSpec(
        name="api_doc_generator",
        title="API Documentation Generator",
        description="Generates OpenAPI-style documentation from code annotations and route definitions.",
        triggers=[
            "generate API docs",
            "document these endpoints",
            "create API reference",
        ],
        steps=[
            "Scan source files for route/endpoint definitions",
            "Extract parameter types, descriptions, and examples",
            "Generate OpenAPI-compatible YAML or Markdown documentation",
            "Validate generated docs for completeness",
        ],
        category="documentation",
        templates=True,
    ),
}


def main():
    parser = argparse.ArgumentParser(
        description="Mythos Skill Forge — scaffold Claude Code skills",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""\
        Examples:
          %(prog)s forge --name my_skill --desc "Does X" --triggers "do X,run X,X please"
          %(prog)s forge --preset code_review
          %(prog)s audit ./skills/my_skill
          %(prog)s list-presets
        """),
    )
    sub = parser.add_subparsers(dest="command", help="Command to run")

    # forge
    forge_p = sub.add_parser("forge", help="Scaffold a new skill")
    forge_p.add_argument("--name", help="Skill name (snake_case)")
    forge_p.add_argument("--title", help="Human-readable title")
    forge_p.add_argument("--desc", help="Skill description")
    forge_p.add_argument("--triggers", help="Comma-separated trigger phrases")
    forge_p.add_argument("--steps", help="Comma-separated workflow steps")
    forge_p.add_argument("--preset", choices=PRESETS.keys(), help="Use a preset skill template")
    forge_p.add_argument("--hooks", action="store_true", help="Generate hook scripts")
    forge_p.add_argument("--templates", action="store_true", help="Generate output templates")
    forge_p.add_argument("--output", default="./skills", help="Output directory (default: ./skills)")
    forge_p.add_argument("--dry-run", action="store_true", help="Preview without writing files")

    # audit
    audit_p = sub.add_parser("audit", help="Audit an existing skill directory")
    audit_p.add_argument("path", help="Path to skill directory")

    # list-presets
    sub.add_parser("list-presets", help="Show available preset templates")

    # demo
    sub.add_parser("demo", help="Run a full demo: forge presets + audit them")

    args = parser.parse_args()

    if args.command == "forge":
        if args.preset:
            spec = PRESETS[args.preset]
        elif args.name and args.desc and args.triggers:
            spec = SkillSpec(
                name=args.name,
                title=args.title or args.name.replace("_", " ").title(),
                description=args.desc,
                triggers=[t.strip() for t in args.triggers.split(",")],
                steps=[s.strip() for s in (args.steps or "Execute the skill workflow,Report results").split(",")],
                hooks=args.hooks,
                templates=args.templates,
            )
        else:
            forge_p.error("Provide --preset OR (--name, --desc, --triggers)")
            return

        output_dir = Path(args.output)
        print(f"\n  Forging skill: {spec.name}")
        print(f"  Output: {output_dir / spec.name}")

        files = forge_skill(spec, output_dir, dry_run=args.dry_run)

        if "_errors" in files:
            print("\n  Validation errors:")
            for e in files["_errors"]:
                print(f"    [-] {e}")
            sys.exit(1)

        print_tree(files)

        if args.dry_run:
            print("  (dry-run mode — no files written)\n")
            for path, content in sorted(files.items()):
                print(f"  --- {path} ---")
                for line in content.split("\n")[:10]:
                    print(f"  | {line}")
                print(f"  | ... ({len(content.split(chr(10)))} lines total)\n")
        else:
            print(f"  Wrote {len(files)} files.\n")

            # Auto-audit
            skill_path = output_dir / spec.name
            report = audit_skill(skill_path)
            print_report(report)

    elif args.command == "audit":
        path = Path(args.path)
        if not path.is_dir():
            print(f"Error: {path} is not a directory")
            sys.exit(1)
        report = audit_skill(path)
        print_report(report)

    elif args.command == "list-presets":
        print("\n  Available presets:")
        print(f"  {'='*50}")
        for key, spec in PRESETS.items():
            print(f"    {key:20s} — {spec.description[:60]}")
        print()

    elif args.command == "demo":
        print("\n" + "="*60)
        print("  MYTHOS SKILL FORGE — FULL DEMO")
        print("="*60)

        output_dir = Path("./demo_output/skills")
        print(f"\n  Output directory: {output_dir}\n")

        # Forge all presets
        for key, spec in PRESETS.items():
            print(f"  >> Forging preset: {key}")
            files = forge_skill(spec, output_dir)
            print_tree(files)

        # Forge a custom skill
        custom = SkillSpec(
            name="ticket_triage",
            title="Ticket Triage Agent",
            description="Automatically categorizes and prioritizes support tickets using context analysis.",
            triggers=[
                "triage this ticket",
                "categorize incoming tickets",
                "prioritize support queue",
            ],
            steps=[
                "Parse the ticket content and metadata",
                "Classify by category (bug, feature, question, billing)",
                "Assign priority (P0-P3) based on impact and urgency",
                "Route to the appropriate team or escalation path",
                "Generate triage summary with reasoning",
            ],
            category="support",
            hooks=True,
            templates=True,
        )
        print(f"  >> Forging custom skill: {custom.name}")
        files = forge_skill(custom, output_dir)
        print_tree(files)

        # Audit all generated skills
        print("\n" + "="*60)
        print("  AUDIT RESULTS")
        print("="*60)

        total_score = 0
        total_max = 0
        for skill_dir in sorted(output_dir.iterdir()):
            if skill_dir.is_dir():
                report = audit_skill(skill_dir)
                print_report(report)
                total_score += report["score"]
                total_max += report["max_score"]

        print(f"\n  Overall: {total_score}/{total_max} across {total_max // 5} skills")
        pct = (total_score / total_max * 100) if total_max else 0
        grade = "A" if pct >= 90 else "B" if pct >= 80 else "C" if pct >= 70 else "F"
        print(f"  Grade: {grade} ({pct:.0f}%)\n")

    else:
        parser.print_help()


if __name__ == "__main__":
    main()
