"""Build a 5-slide explainer deck per skill (.pptx)."""
from __future__ import annotations

import logging
from pathlib import Path

from pptx import Presentation
from pptx.util import Inches, Pt

from trendforge import store

log = logging.getLogger(__name__)

ROOT = Path(__file__).resolve().parents[2]
DECK_DIR = ROOT / "output" / "decks"


def _add_text_slide(prs, title: str, body_lines: list[str]) -> None:
    layout = prs.slide_layouts[1]  # title + content
    slide = prs.slides.add_slide(layout)
    slide.shapes.title.text = title
    body = slide.placeholders[1].text_frame
    body.text = body_lines[0] if body_lines else ""
    for line in body_lines[1:]:
        p = body.add_paragraph()
        p.text = line


def best_fit_project(skill_name: str, tags: list[str]) -> str:
    text = f"{skill_name} {' '.join(tags)}".lower()
    if any(k in text for k in ("voice", "tts", "stt", "interview", "audio")):
        return "ARIA (voice interviewer)"
    if any(k in text for k in ("vlsi", "risc-v", "soc", "npu", "glasses", "vision")):
        return "Smart Glasses (RISC-V SoC)"
    if any(k in text for k in ("sales", "lead", "outreach", "email", "naukri", "rag")):
        return "PitchBot (B2B outreach)"
    return "TrendForge (this system)"


def build_deck(skill_id: int, db_path=None) -> Path | None:
    """Build a 5-slide deck for one skill. Uses python-pptx (no external API)."""
    db = db_path or store.DB_PATH
    DECK_DIR.mkdir(parents=True, exist_ok=True)
    with store.get_conn(db) as conn:
        skill = conn.execute(
            "SELECT * FROM skills WHERE id = ?", (skill_id,)
        ).fetchone()
        if not skill:
            return None
        item = store.row_to_dict(
            conn.execute("SELECT * FROM items WHERE id = ?", (skill["item_id"],)).fetchone()
        ) or {}
        proto = conn.execute(
            "SELECT * FROM prototypes WHERE skill_id = ? ORDER BY id DESC LIMIT 1",
            (skill_id,),
        ).fetchone()

    name = skill["skill_name"]
    tags = item.get("tags") or []
    if isinstance(tags, str):
        tags = []
    project = best_fit_project(name, tags)

    prs = Presentation()
    # Title slide
    title_layout = prs.slide_layouts[0]
    title_slide = prs.slides.add_slide(title_layout)
    title_slide.shapes.title.text = name.replace("_", " ").title()
    title_slide.placeholders[1].text = f"Generated by TrendForge from {item.get('source')}"

    _add_text_slide(
        prs,
        "1. What problem this solves",
        [
            f"Source: {item.get('title') or '(untitled)'}",
            f"URL: {item.get('url')}",
            f"Tags: {', '.join(tags) if tags else '—'}",
        ],
    )
    _add_text_slide(
        prs,
        "2. How it works",
        [
            "See SKILL.md for the full walk-through.",
            f"Skill folder: output/skills/{name}/",
            "Self-contained, runnable, follows Anthropic skill conventions.",
        ],
    )
    _add_text_slide(
        prs,
        "3. Live demo",
        [
            f"Prototype: output/prototypes/{name}/",
            "Run: bash run.sh",
            f"Status: {'runs OK' if (proto and proto['runs_successfully']) else 'stub — please verify'}",
        ],
    )
    _add_text_slide(
        prs,
        f"4. Why it matters for {project}",
        [
            f"Best fit: {project}",
            "Consider integrating after one production day of dogfooding.",
        ],
    )
    _add_text_slide(
        prs,
        "5. How to integrate",
        [
            f"1. Copy output/skills/{name}/ into the target repo's .claude/skills/",
            "2. Reference triggers in CLAUDE.md or your slash commands.",
            f"3. Source for follow-up: {item.get('url')}",
        ],
    )

    out = DECK_DIR / f"{name}.pptx"
    prs.save(str(out))

    # Update prototype row with deck path
    with store.get_conn(db) as conn:
        if proto:
            conn.execute(
                "UPDATE prototypes SET deck_path = ? WHERE id = ?",
                (str(out), proto["id"]),
            )
            conn.commit()
    return out


def build_decks(db_path=None) -> list[Path]:
    """Build a deck for every skill that doesn't yet have one."""
    db = db_path or store.DB_PATH
    out: list[Path] = []
    with store.get_conn(db) as conn:
        rows = conn.execute(
            """
            SELECT s.id FROM skills s
            LEFT JOIN prototypes p ON p.skill_id = s.id
            WHERE p.deck_path IS NULL OR p.deck_path = ''
            """
        ).fetchall()
    for r in rows:
        p = build_deck(r["id"], db_path=db_path)
        if p is not None:
            out.append(p)
    log.info("Built %d decks", len(out))
    return out
