"""IPTC Digital Source Type vocabulary for content provenance classification."""

# Maps IPTC digital source type codes to human-readable labels and AI classification
SOURCE_TYPES = {
    "trainedAlgorithmicMedia": {
        "label": "AI-generated (trained algorithm)",
        "is_ai": True,
        "description": "Media created by a trained AI model (e.g., DALL-E, Midjourney, Stable Diffusion)",
    },
    "compositeSynthetic": {
        "label": "Composite with AI elements",
        "is_ai": True,
        "description": "Real media combined with AI-generated elements",
    },
    "algorithmicMedia": {
        "label": "Algorithmically generated",
        "is_ai": False,
        "description": "Generated by non-AI algorithms (e.g., fractals, procedural)",
    },
    "digitalCapture": {
        "label": "Digital camera capture",
        "is_ai": False,
        "description": "Captured directly by a digital camera or scanner",
    },
    "digitalArt": {
        "label": "Digital art (human-created)",
        "is_ai": False,
        "description": "Created by a human using digital tools",
    },
    "minorHumanEdits": {
        "label": "Minor human edits",
        "is_ai": False,
        "description": "Original content with minor human edits (crop, color, etc.)",
    },
}


def classify_source_type(source_type: str) -> dict:
    """Look up a digital source type and return its classification."""
    if source_type in SOURCE_TYPES:
        return SOURCE_TYPES[source_type]
    return {
        "label": f"Unknown ({source_type})",
        "is_ai": None,
        "description": "Unrecognized digital source type",
    }


def is_ai_generated(source_type: str) -> bool | None:
    """Return True if the source type indicates AI generation."""
    info = classify_source_type(source_type)
    return info["is_ai"]
