"""
Rare Disease Diagnostic Engine

Matches patient phenotype profiles against a knowledge base of rare diseases,
producing ranked differential diagnoses with phenotype overlap scores,
atypical features, and recommended next steps.

Inspired by Boston Children's Hospital's AI-assisted diagnostic approach.
"""

import json
from dataclasses import dataclass, field, asdict
from typing import Optional
from hpo_data import HPO_TERMS, RARE_DISEASES, RECOMMENDED_TESTS


@dataclass
class PatientProfile:
    patient_id: str
    hpo_terms: list[str]
    negative_findings: list[str] = field(default_factory=list)
    age_onset: str = "Unknown"
    sex: str = "Unknown"
    genetic_tests_done: list[str] = field(default_factory=list)
    prior_diagnoses_excluded: list[str] = field(default_factory=list)

    def describe(self) -> str:
        pos = [f"  {t} — {HPO_TERMS.get(t, {}).get('name', '?')}" for t in self.hpo_terms]
        neg = [f"  {t} — {HPO_TERMS.get(t, {}).get('name', '?')}" for t in self.negative_findings]
        lines = [
            f"Patient {self.patient_id}",
            f"  Sex: {self.sex}  |  Onset: {self.age_onset}",
            f"  Genetic tests done: {', '.join(self.genetic_tests_done) or 'None'}",
            "  Phenotype (positive):",
            *pos,
        ]
        if neg:
            lines += ["  Phenotype (negative/absent):", *neg]
        return "\n".join(lines)


@dataclass
class CandidateDiagnosis:
    rank: int
    disease_name: str
    omim: str
    orpha: str
    gene: str
    phenotype_overlap: float  # 0-1
    matching_hpo: list[str]
    atypical_features: list[str]
    contradicted_by_negatives: list[str]
    recommended_tests: list[str]
    confidence: str  # high / medium / low
    description: str


def compute_overlap(patient: PatientProfile, disease: dict) -> tuple[float, list[str], list[str], list[str]]:
    """Compute Jaccard-like phenotype overlap between patient and disease."""
    patient_set = set(patient.hpo_terms)
    disease_set = set(disease["phenotype"])
    negative_set = set(patient.negative_findings)

    matching = patient_set & disease_set
    # Features the disease expects but patient doesn't have
    atypical = disease_set - patient_set
    # Features the disease expects but patient explicitly lacks
    contradicted = disease_set & negative_set

    union = patient_set | disease_set
    overlap = len(matching) / len(union) if union else 0.0

    # Penalize contradictions
    if contradicted:
        overlap *= max(0.3, 1.0 - 0.25 * len(contradicted))

    return overlap, sorted(matching), sorted(atypical), sorted(contradicted)


def rank_diagnoses(patient: PatientProfile, top_n: int = 5) -> list[CandidateDiagnosis]:
    """Rank diseases by phenotype overlap with the patient profile."""
    scored = []
    for disease in RARE_DISEASES:
        if disease["name"] in patient.prior_diagnoses_excluded:
            continue

        overlap, matching, atypical, contradicted = compute_overlap(patient, disease)

        if overlap < 0.05:
            continue

        if overlap >= 0.5:
            confidence = "high"
        elif overlap >= 0.3:
            confidence = "medium"
        else:
            confidence = "low"

        gene = disease["gene"]
        tests = RECOMMENDED_TESTS.get(gene, [f"{gene} sequencing"])
        # Remove tests already done
        tests = [t for t in tests if not any(done.lower() in t.lower() for done in patient.genetic_tests_done)]

        scored.append(CandidateDiagnosis(
            rank=0,
            disease_name=disease["name"],
            omim=disease["omim"],
            orpha=disease["orpha"],
            gene=gene,
            phenotype_overlap=round(overlap, 3),
            matching_hpo=matching,
            atypical_features=atypical,
            contradicted_by_negatives=contradicted,
            recommended_tests=tests or ["No additional tests — consider clinical review"],
            confidence=confidence,
            description=disease["description"],
        ))

    scored.sort(key=lambda c: c.phenotype_overlap, reverse=True)
    for i, c in enumerate(scored[:top_n], 1):
        c.rank = i

    return scored[:top_n]


def generate_report(patient: PatientProfile, candidates: list[CandidateDiagnosis]) -> dict:
    """Generate a structured diagnostic report."""
    return {
        "patient_id": patient.patient_id,
        "phenotype_count": len(patient.hpo_terms),
        "negative_findings_count": len(patient.negative_findings),
        "candidates_evaluated": len(RARE_DISEASES),
        "differential_diagnoses": [asdict(c) for c in candidates],
        "summary": _build_summary(patient, candidates),
        "next_steps": _build_next_steps(candidates),
        "disclaimer": (
            "This report is generated by an AI-assisted tool and is intended "
            "to support — not replace — clinical decision-making. All candidate "
            "diagnoses must be reviewed by a qualified clinician."
        ),
    }


def _build_summary(patient: PatientProfile, candidates: list[CandidateDiagnosis]) -> str:
    if not candidates:
        return "No strong candidates found. Consider expanding phenotype capture or consulting a specialist."
    top = candidates[0]
    lines = [
        f"Top candidate: {top.disease_name} ({top.omim}) with "
        f"{top.phenotype_overlap:.0%} phenotype overlap.",
    ]
    if len(candidates) > 1:
        others = ", ".join(c.disease_name for c in candidates[1:3])
        lines.append(f"Also consider: {others}.")
    if top.contradicted_by_negatives:
        neg_names = [HPO_TERMS.get(h, {}).get("name", h) for h in top.contradicted_by_negatives]
        lines.append(f"Note: patient explicitly lacks {', '.join(neg_names)}, which is expected in {top.disease_name}.")
    return " ".join(lines)


def _build_next_steps(candidates: list[CandidateDiagnosis]) -> list[str]:
    steps = []
    seen_tests = set()
    for c in candidates[:3]:
        for t in c.recommended_tests[:2]:
            if t not in seen_tests:
                steps.append(f"[{c.disease_name}] {t}")
                seen_tests.add(t)
    steps.append("Present differential to multidisciplinary team for review.")
    steps.append("Re-evaluate if new phenotypic findings emerge.")
    return steps


def format_report_text(report: dict) -> str:
    """Pretty-print a diagnostic report for terminal output."""
    lines = [
        "=" * 72,
        "  RARE DISEASE DIAGNOSTIC REPORT",
        "=" * 72,
        f"  Patient: {report['patient_id']}",
        f"  Phenotypes entered: {report['phenotype_count']}  |  "
        f"Negatives: {report['negative_findings_count']}",
        f"  Diseases screened: {report['candidates_evaluated']}",
        "-" * 72,
    ]

    for dx in report["differential_diagnoses"]:
        overlap_pct = f"{dx['phenotype_overlap']:.0%}"
        lines += [
            f"\n  #{dx['rank']}  {dx['disease_name']}  [{dx['confidence'].upper()} confidence]",
            f"      OMIM: {dx['omim']}  |  Orphanet: {dx['orpha']}  |  Gene: {dx['gene']}",
            f"      Overlap: {overlap_pct}",
            f"      Matching HPO: {', '.join(dx['matching_hpo'])}",
        ]
        matching_names = [HPO_TERMS.get(h, {}).get("name", h) for h in dx["matching_hpo"]]
        lines.append(f"        ({', '.join(matching_names)})")

        if dx["atypical_features"]:
            atyp_names = [HPO_TERMS.get(h, {}).get("name", h) for h in dx["atypical_features"]]
            lines.append(f"      Atypical/missing: {', '.join(atyp_names)}")

        if dx["contradicted_by_negatives"]:
            contra_names = [HPO_TERMS.get(h, {}).get("name", h) for h in dx["contradicted_by_negatives"]]
            lines.append(f"      CONTRADICTED by negatives: {', '.join(contra_names)}")

        lines.append(f"      Recommended tests: {'; '.join(dx['recommended_tests'])}")
        lines.append(f"      Description: {dx['description']}")

    lines += [
        "\n" + "-" * 72,
        "  SUMMARY",
        f"  {report['summary']}",
        "",
        "  NEXT STEPS",
    ]
    for step in report["next_steps"]:
        lines.append(f"    - {step}")

    lines += [
        "",
        "  DISCLAIMER",
        f"  {report['disclaimer']}",
        "=" * 72,
    ]
    return "\n".join(lines)
