"""
Healthcare Clinical Workflow Optimizer - Core Engine

AI-powered workflow automation that drafts clinical documentation,
patient messages, and care coordination artifacts for clinician review.
Uses structured templates and mock AI generation for demo purposes.
"""

import json
from datetime import datetime, timezone
from typing import Optional


class AuditLogger:
    """HIPAA-aware audit trail. Logs actions without storing PHI."""

    def __init__(self):
        self.entries: list[dict] = []

    def log(self, action: str, clinician_id: str, workflow_type: str,
            metadata: Optional[dict] = None):
        entry = {
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "action": action,
            "clinician_id": clinician_id,
            "workflow_type": workflow_type,
            "metadata": metadata or {},
        }
        self.entries.append(entry)
        return entry

    def summary(self) -> dict:
        return {
            "total_events": len(self.entries),
            "by_action": self._count_by("action"),
            "by_workflow": self._count_by("workflow_type"),
        }

    def _count_by(self, key: str) -> dict:
        counts: dict[str, int] = {}
        for e in self.entries:
            val = e[key]
            counts[val] = counts.get(val, 0) + 1
        return counts


class MockAIClient:
    """Simulates an LLM backend for clinical text generation.
    In production this would call Claude API with a BAA in place."""

    TEMPLATES = {
        "progress_note": """PROGRESS NOTE — {date}
Patient: {patient_name} | MRN: {mrn}
Provider: {provider}

SUBJECTIVE:
Patient presents with {chief_complaint}. Reports {symptom_duration} duration.
{additional_history}

OBJECTIVE:
Vitals: BP {bp}, HR {hr}, Temp {temp}, SpO2 {spo2}
{exam_findings}

ASSESSMENT:
{assessment}

PLAN:
{plan}

[Draft generated by AI — requires clinician review before signing]""",

        "discharge_summary": """DISCHARGE SUMMARY
Patient: {patient_name} | MRN: {mrn}
Admission: {admit_date} | Discharge: {discharge_date}
Attending: {provider}

REASON FOR ADMISSION:
{reason_for_admission}

HOSPITAL COURSE:
{hospital_course}

DISCHARGE DIAGNOSIS:
{discharge_diagnosis}

DISCHARGE MEDICATIONS:
{medications}

FOLLOW-UP INSTRUCTIONS:
{follow_up}

[Draft generated by AI — requires clinician review before signing]""",

        "patient_message": """Dear {patient_name},

Thank you for your recent visit on {visit_date} with {provider}.

{message_body}

If you have questions, please call our office at {office_phone} or send a message through your patient portal.

Take care,
{provider}
{department}

[Draft generated by AI — reviewed and approved by your care team]""",

        "referral_letter": """REFERRAL LETTER
Date: {date}
From: {provider}, {department}
To: {referral_to}

RE: {patient_name} (DOB: {dob}, MRN: {mrn})

Dear Colleague,

I am referring the above patient for evaluation of {referral_reason}.

RELEVANT HISTORY:
{relevant_history}

CURRENT MEDICATIONS:
{medications}

Please evaluate and advise. Thank you for your excellent care of our shared patient.

Sincerely,
{provider}

[Draft generated by AI — requires clinician review before sending]""",

        "care_plan": """CARE PLAN — {patient_name}
Created: {date} | Provider: {provider}

ACTIVE PROBLEMS:
{problems}

GOALS:
{goals}

INTERVENTIONS:
{interventions}

FOLLOW-UP SCHEDULE:
{follow_up_schedule}

CARE TEAM:
{care_team}

[Draft generated by AI — requires clinician review and patient discussion]""",

        "after_visit_summary": """YOUR VISIT SUMMARY — {visit_date}

Hi {patient_name},

Here is a summary of your visit today with {provider}.

WHAT WE DISCUSSED:
{discussion_summary}

YOUR NEXT STEPS:
{patient_instructions}

MEDICATIONS:
{medications}

YOUR NEXT APPOINTMENT:
{next_appointment}

Questions? Call us at {office_phone} or message through your portal.

[This summary was drafted by AI and reviewed by your care team]""",
    }

    def generate(self, workflow_type: str, context: dict) -> str:
        template = self.TEMPLATES.get(workflow_type)
        if not template:
            return f"[No template for workflow type: {workflow_type}]"
        # Fill template, using placeholder for missing keys
        import re
        def replacer(match):
            key = match.group(1)
            return str(context.get(key, f"[{key}]"))
        return re.sub(r"\{(\w+)\}", replacer, template)


class ClinicalWorkflowOptimizer:
    """Main orchestrator for healthcare workflow automation."""

    SUPPORTED_WORKFLOWS = [
        "progress_note",
        "discharge_summary",
        "patient_message",
        "referral_letter",
        "care_plan",
        "after_visit_summary",
    ]

    ROLE_PERMISSIONS = {
        "physician": SUPPORTED_WORKFLOWS.copy(),
        "nurse": ["progress_note", "patient_message", "care_plan", "after_visit_summary"],
        "admin": ["patient_message", "after_visit_summary"],
        "care_coordinator": ["care_plan", "referral_letter", "patient_message"],
    }

    def __init__(self):
        self.ai_client = MockAIClient()
        self.audit = AuditLogger()
        self.drafts: list[dict] = []

    def generate_draft(self, workflow_type: str, context: dict,
                       clinician_id: str, role: str = "physician") -> dict:
        """Generate a draft document for clinician review."""
        # Validate workflow type
        if workflow_type not in self.SUPPORTED_WORKFLOWS:
            raise ValueError(
                f"Unsupported workflow: {workflow_type}. "
                f"Supported: {', '.join(self.SUPPORTED_WORKFLOWS)}"
            )

        # Check role-based access
        allowed = self.ROLE_PERMISSIONS.get(role, [])
        if workflow_type not in allowed:
            self.audit.log("access_denied", clinician_id, workflow_type,
                           {"role": role})
            raise PermissionError(
                f"Role '{role}' cannot generate '{workflow_type}'. "
                f"Allowed: {', '.join(allowed)}"
            )

        # Generate draft
        self.audit.log("draft_requested", clinician_id, workflow_type)
        draft_text = self.ai_client.generate(workflow_type, context)
        self.audit.log("draft_generated", clinician_id, workflow_type)

        result = {
            "id": len(self.drafts) + 1,
            "draft": draft_text,
            "workflow_type": workflow_type,
            "clinician_id": clinician_id,
            "role": role,
            "requires_review": True,
            "status": "pending_clinician_approval",
            "created_at": datetime.now(timezone.utc).isoformat(),
            "word_count": len(draft_text.split()),
        }
        self.drafts.append(result)
        return result

    def approve_draft(self, draft_id: int, clinician_id: str,
                      edits: Optional[str] = None) -> dict:
        """Clinician approves (optionally edits) a draft."""
        draft = self._get_draft(draft_id)
        if edits:
            draft["draft"] = edits
            draft["was_edited"] = True
            self.audit.log("draft_edited", clinician_id, draft["workflow_type"])
        else:
            draft["was_edited"] = False

        draft["status"] = "approved"
        draft["approved_by"] = clinician_id
        draft["approved_at"] = datetime.now(timezone.utc).isoformat()
        self.audit.log("draft_approved", clinician_id, draft["workflow_type"])
        return draft

    def reject_draft(self, draft_id: int, clinician_id: str,
                     reason: str = "") -> dict:
        """Clinician rejects a draft."""
        draft = self._get_draft(draft_id)
        draft["status"] = "rejected"
        draft["rejected_by"] = clinician_id
        draft["rejection_reason"] = reason
        self.audit.log("draft_rejected", clinician_id, draft["workflow_type"],
                       {"reason": reason})
        return draft

    def get_metrics(self) -> dict:
        """Dashboard metrics for workflow optimization impact."""
        if not self.drafts:
            return {"message": "No drafts generated yet"}

        total = len(self.drafts)
        approved = sum(1 for d in self.drafts if d["status"] == "approved")
        rejected = sum(1 for d in self.drafts if d["status"] == "rejected")
        edited = sum(1 for d in self.drafts if d.get("was_edited", False))
        avg_words = sum(d["word_count"] for d in self.drafts) / total

        # Estimate time saved: ~3 min saved per approved draft
        est_minutes_saved = approved * 3

        return {
            "total_drafts": total,
            "approved": approved,
            "rejected": rejected,
            "pending": total - approved - rejected,
            "edit_rate": f"{edited / max(approved, 1) * 100:.0f}%",
            "avg_word_count": round(avg_words),
            "est_minutes_saved": est_minutes_saved,
            "est_hours_saved_per_month": round(est_minutes_saved * 20 / 60, 1),
            "workflow_breakdown": self.audit.summary()["by_workflow"],
        }

    def _get_draft(self, draft_id: int) -> dict:
        for d in self.drafts:
            if d["id"] == draft_id:
                return d
        raise ValueError(f"Draft {draft_id} not found")
